### ISSUE TITLE
Pagination change issue

### ISSUE THREAD

**Issue by fr3em1nd** [bleistivt/InfiniteScroll#1]
hi I found a minor bug, when i changed my per page view from 50 -> 10 , when i go directly to page 3 which in my case is nonexistent, it will remove the comment box
![2015-03-05_9-36-54](https://cloud.githubusercontent.com/assets/2801155/6497482/4c22a554-c31b-11e4-80ff-6462c4b85735.png)

**Comment by bleistivt** [comment]
How are you going directly to page 3?

If it is nonexistent, it shouldn't be possible using the jump menu.

**Comment by fr3em1nd** [comment]
example if my page 3 is indexed by google or something, im just making some possible scenarios , i think this is not very important. but might be worth looking
