### ISSUE TITLE
How can i disable Navigation in Infinite Scroll v2.2 in Vanilla v3.1 ?

### ISSUE THREAD

**Issue by 11assets** [bleistivt/InfiniteScroll#2]
1. Current page number is not showing. Instead its showing ? mark. What to do?
2. How can I disable entire Navigation bar?

Need help. Thanks in advance.

**Comment by bleistivt** [comment]
fixed in c544e78fbaedc3035708d4dbd3fd29e5975e8538

**Comment by bleistivt** [comment]
If you still want to hide the navigation, add this to your stylesheet:

    #InfScrollNav {display:none;}
